### ISSUE TITLE
Scoreboard is in reverse order

### ISSUE THREAD

**Issue by AmiralBl3ndic** [AmiralBl3ndic/Vinaigrette-Client#1]
Currently the scoreboard displays all the players in a room as well as their score, but they are ordered so the player with the highest score is at the bottom of the scoreboard.

This should be fixed so that players with the highest score are at the top of the scoreboard.

**Comment by RookyRaccoon** [comment]
Set username

**Comment by AmiralBl3ndic** [comment]
This was because of a default sorting function that has now been set to sort in reverse order.

The top scores are now at the top of the scoreboard
